(function($) {
    $(document).ready(function() {
	
	$('#European_common_reed').scianimator({
	    'images': ['images/European_common_reed1.png', 'images/European_common_reed2.png', 'images/European_common_reed3.png', 'images/European_common_reed4.png', 'images/European_common_reed5.png', 'images/European_common_reed6.png', 'images/European_common_reed7.png', 'images/European_common_reed8.png', 'images/European_common_reed9.png', 'images/European_common_reed10.png', 'images/European_common_reed11.png', 'images/European_common_reed12.png', 'images/European_common_reed13.png', 'images/European_common_reed14.png', 'images/European_common_reed15.png', 'images/European_common_reed16.png', 'images/European_common_reed17.png', 'images/European_common_reed18.png', 'images/European_common_reed19.png', 'images/European_common_reed20.png', 'images/European_common_reed21.png', 'images/European_common_reed22.png', 'images/European_common_reed23.png', 'images/European_common_reed24.png', 'images/European_common_reed25.png', 'images/European_common_reed26.png', 'images/European_common_reed27.png', 'images/European_common_reed28.png', 'images/European_common_reed29.png', 'images/European_common_reed30.png', 'images/European_common_reed31.png', 'images/European_common_reed32.png', 'images/European_common_reed33.png', 'images/European_common_reed34.png', 'images/European_common_reed35.png', 'images/European_common_reed36.png', 'images/European_common_reed37.png', 'images/European_common_reed38.png', 'images/European_common_reed39.png', 'images/European_common_reed40.png', 'images/European_common_reed41.png', 'images/European_common_reed42.png', 'images/European_common_reed43.png', 'images/European_common_reed44.png', 'images/European_common_reed45.png', 'images/European_common_reed46.png', 'images/European_common_reed47.png', 'images/European_common_reed48.png', 'images/European_common_reed49.png', 'images/European_common_reed50.png', 'images/European_common_reed51.png', 'images/European_common_reed52.png', 'images/European_common_reed53.png', 'images/European_common_reed54.png', 'images/European_common_reed55.png', 'images/European_common_reed56.png', 'images/European_common_reed57.png', 'images/European_common_reed58.png', 'images/European_common_reed59.png', 'images/European_common_reed60.png', 'images/European_common_reed61.png', 'images/European_common_reed62.png', 'images/European_common_reed63.png', 'images/European_common_reed64.png', 'images/European_common_reed65.png'],
	    'width': 600,
	    'delay': 1000,
	    'loopMode': 'loop'
	});
	$('#European_common_reed').scianimator('play');
    });
})(jQuery);
